# Dockerfile.opentracker
FROM debian:buster-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    cvs \
    libowfat-dev \
    && rm -rf /var/lib/apt/lists/*

RUN cvs -d :pserver:cvs@cvs.fefe.de:/cvs -z9 co libowfat
RUN cd libowfat && make

RUN cvs -d :pserver:cvs@cvs.fefe.de:/cvs -z9 co opentracker
RUN cd opentracker && make

EXPOSE 6969

CMD ["./opentracker/opentracker", "-i", "0.0.0.0"]
