# Use the official Alpine image as a base
FROM alpine:latest

# Install aria2
RUN apk add --no-cache aria2

# Create directories for files and torrents
RUN mkdir -p /files /torrents

# Copy the test file and torrent file into the container
COPY files/pengting.mp4 /files/
COPY torrents/pengting.torrent /torrents/

CMD sleep 10 && aria2c -V --seed-ratio=0.0 --bt-tracker=http://opentracker:6969/announce -d /files /torrents/pengting.torrent
