name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ libcurl4-openssl-dev libssl-dev libgtest-dev cmake libboost-all-dev gtk4

    - name: Compile GTest
      run: |
        cd /usr/src/googletest/googletest
        sudo mkdir -p build
        cd build
        sudo cmake ..
        sudo make
        sudo cp lib/libgtest.a lib/libgtest_main.a /usr/lib/
        sudo mkdir -p /usr/local/lib/googletest
        sudo ln -s /usr/lib/libgtest.a /usr/local/lib/googletest/libgtest.a
        sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/googletest/libgtest_main.a

    - name: Build and Run Tests
      run: |
        make test

    - name: Clean up
      run: make clean
